ame: iapetus - default

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 5 * * 1" # At 03:00 on Monday
  workflow_dispatch:

jobs:
  build-snapshot:
    uses: linked-planet/github-workflows/.github/workflows/build-snapshot.yml@v6

  notify-slack:
    needs: e2e-testing
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - name: Notify Slack
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: iRoachie/slack-github-actions@v2.3.2
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ github.token }}