name: iapetus - default

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 6 * * 1" # At 03:00 on Monday
  workflow_dispatch:

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Maven Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml', '*/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: corretto

      - name: Build POM
        run: mvn package -B

  notify-slack:
    needs: build-snapshot
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - name: Notify Slack
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: iRoachie/slack-github-actions@v2.3.2
        env:
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ github.token }}